"""
This type stub file was generated by pyright.
"""

class DrtGlueDemo(object):
    def __init__(self, examples) -> None:
        ...
    
    def destroy(self, *e):
        ...
    
    def prev(self, *e):
        ...
    
    def next(self, *e):
        ...
    
    def about(self, *e):
        ...
    
    def postscript(self, *e):
        ...
    
    def mainloop(self, *args, **kwargs):
        """
        Enter the Tkinter mainloop.  This function must be called if
        this demo is created from a non-interactive program (e.g.
        from a secript); otherwise, the demo will close as soon as
        the script completes.
        """
        ...
    
    def resize(self, size=...):
        ...
    


class DrsWidget(object):
    def __init__(self, canvas, drs, **attribs) -> None:
        ...
    
    def draw(self):
        ...
    
    def clear(self):
        ...
    


def demo():
    ...

if __name__ == "__main__":
    ...
