"""
This type stub file was generated by pyright.
"""

class FStructure(dict):
    def safeappend(self, key, item):
        """
        Append 'item' to the list at 'key'.  If no list exists for 'key', then
        construct one.
        """
        ...
    
    def __setitem__(self, key, value):
        ...
    
    def __getitem__(self, key):
        ...
    
    def __contains__(self, key):
        ...
    
    def to_glueformula_list(self, glue_dict):
        ...
    
    def to_depgraph(self, rel=...):
        ...
    
    @staticmethod
    def read_depgraph(depgraph):
        ...
    
    def __repr__(self):
        ...
    
    def __str__(self) -> str:
        ...
    
    def pretty_format(self, indent=...):
        ...
    


def demo_read_depgraph():
    ...

if __name__ == "__main__":
    ...
