"""
This type stub file was generated by pyright.
"""

def skolemize(expression, univ_scope=..., used_variables=...):
    """
    Skolemize the expression and convert to conjunctive normal form (CNF)
    """
    ...

def to_cnf(first, second):
    """
    Convert this split disjunction to conjunctive normal form (CNF)
    """
    ...

