"""
This type stub file was generated by pyright.
"""

from nltk.sentiment.sentiment_analyzer import SentimentAnalyzer
from nltk.sentiment.vader import SentimentIntensityAnalyzer

"""
NLTK Sentiment Analysis Package

"""
