"""
This type stub file was generated by pyright.
"""

from nltk.draw.util import ColorizedList

"""
Visualization tools for CFGs.
"""
class ProductionList(ColorizedList):
    ARROW = ...


_CFGEditor_HELP = ...
class CFGEditor(object):
    """
    A dialog window for creating and editing context free grammars.
    ``CFGEditor`` imposes the following restrictions:

    - All nonterminals must be strings consisting of word
      characters.
    - All terminals must be strings consisting of word characters
      and space characters.
    """
    ARROW = ...
    _LHS_RE = ...
    _ARROW_RE = ...
    _PRODUCTION_RE = ...
    _TOKEN_RE = ...
    _BOLD = ...
    def __init__(self, parent, cfg=..., set_cfg_callback=...) -> None:
        ...
    


class CFGDemo(object):
    def __init__(self, grammar, text) -> None:
        ...
    
    def reset_workspace(self):
        ...
    
    def workspace_markprod(self, production):
        ...
    
    def destroy(self, *args):
        ...
    
    def mainloop(self, *args, **kwargs):
        ...
    


def demo2():
    ...

def demo():
    ...

def demo3():
    ...

if __name__ == "__main__":
    ...
