"""
This type stub file was generated by pyright.
"""

"""
Authentication utilities to accompany :module:`twitterclient`.
"""
def credsfromfile(creds_file=..., subdir=..., verbose=...):
    """
    Convenience function for authentication
    """
    ...

class Authenticate(object):
    """
    Methods for authenticating with Twitter.
    """
    def __init__(self) -> None:
        ...
    
    def load_creds(self, creds_file=..., subdir=..., verbose=...):
        """
        Read OAuth credentials from a text file.

        ::
           File format for OAuth 1
           =======================
           app_key=YOUR_APP_KEY
           app_secret=YOUR_APP_SECRET
           oauth_token=OAUTH_TOKEN
           oauth_token_secret=OAUTH_TOKEN_SECRET


        ::
           File format for OAuth 2
           =======================

           app_key=YOUR_APP_KEY
           app_secret=YOUR_APP_SECRET
           access_token=ACCESS_TOKEN

        :param str file_name: File containing credentials. ``None`` (default) reads\
        data from `TWITTER/'credentials.txt'`
        """
        ...
    


def add_access_token(creds_file=...):
    """
    For OAuth 2, retrieve an access token for an app and append it to a
    credentials file.
    """
    ...

def guess_path(pth):
    """
    If the path is not absolute, guess that it is a subdirectory of the
    user's home directory.

    :param str pth: The pathname of the directory where files of tweets should be written
    """
    ...

