version: "3.4"

services:
  semantic-search-api:
    image: semantic_search_api
    container_name: semantic_search_api
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/api
      - ../data:/app/data
