#!/bin/bash

generate_arxiv() {
    echo $@
    
    ./context_delete        arxiv $@
    ./context_create        arxiv $@
    ./context_execute       arxiv $@
    
    #./word_document_create  $@
    #./context_query         $@
    
    #./features_extract       $@
}

generate_arxiv neural networks
# generate graph database
# generate neural networks word frequency
# generate ontology modelling modeling owl rdf
# generate ontology modelling modeling wordnet
# generate ontology reasoning
# generate semantic distance
# generate semantic distance ontology neural networks
# generate semantic distance ontology wordnet neural networks
# generate semantic distance ontology wordnet semantic meaning
# generate semantic distance ontology wordnet semantic metrics
# generate semantic ontology matching cider
# generate semantic ontology matching cromatcher
# generate semantic ontology matching multifarm