"""
This type stub file was generated by pyright.
"""

import click

CONTEXT_SETTINGS = ...
@click.group(context_settings=CONTEXT_SETTINGS)
@click.version_option()
def cli():
    ...

@cli.command("tokenize")
@click.option("--language", "-l", default="en", help="The language for the Punkt sentence tokenization.")
@click.option("--preserve-line", "-l", default=True, is_flag=True, help="An option to keep the preserve the sentence and not sentence tokenize it.")
@click.option("--processes", "-j", default=1, help="No. of processes.")
@click.option("--encoding", "-e", default="utf8", help="Specify encoding of file.")
@click.option("--delimiter", "-d", default=" ", help="Specify delimiter to join the tokens.")
def tokenize_file(language, preserve_line, processes, encoding, delimiter):
    """ This command tokenizes text stream using nltk.word_tokenize """
    ...

