"""
This type stub file was generated by pyright.
"""

from nltk.corpus.reader import CorpusReader

"""
An NLTK interface for the n-gram statistics gathered from
the corpora for each language using An Crubadan.

There are multiple potential applications for the data but
this reader was created with the goal of using it in the
context of language identification.

For details about An Crubadan, this data, and its potential uses, see:
http://borel.slu.edu/crubadan/index.html
"""
class CrubadanCorpusReader(CorpusReader):
    """
    A corpus reader used to access language An Crubadan n-gram files.
    """
    _LANG_MAPPER_FILE = ...
    _all_lang_freq = ...
    def __init__(self, root, fileids, encoding=..., tagset=...) -> None:
        ...
    
    def lang_freq(self, lang):
        """ Return n-gram FreqDist for a specific language
            given ISO 639-3 language code """
        ...
    
    def langs(self):
        """ Return a list of supported languages as ISO 639-3 codes """
        ...
    
    def iso_to_crubadan(self, lang):
        """ Return internal Crubadan code based on ISO 639-3 code """
        ...
    
    def crubadan_to_iso(self, lang):
        """ Return ISO 639-3 code given internal Crubadan code """
        ...
    


