"""
This type stub file was generated by pyright.
"""

from nltk.corpus.reader.api import *

"""
Corpus reader for the Information Extraction and Entity Recognition Corpus.

NIST 1999 Information Extraction: Entity Recognition Evaluation
http://www.itl.nist.gov/iad/894.01/tests/ie-er/er_99/er_99.htm

This corpus contains the NEWSWIRE development test data for the
NIST 1999 IE-ER Evaluation.  The files were taken from the
subdirectory: /ie_er_99/english/devtest/newswire/*.ref.nwt
and filenames were shortened.

The corpus contains the following files: APW_19980314, APW_19980424,
APW_19980429, NYT_19980315, NYT_19980403, and NYT_19980407.
"""
titles = ...
documents = ...
class IEERDocument(object):
    def __init__(self, text, docno=..., doctype=..., date_time=..., headline=...) -> None:
        ...
    
    def __repr__(self):
        ...
    


class IEERCorpusReader(CorpusReader):
    """
    """
    def raw(self, fileids=...):
        ...
    
    def docs(self, fileids=...):
        ...
    
    def parsed_docs(self, fileids=...):
        ...
    


