"""
This type stub file was generated by pyright.
"""

from nltk.corpus.reader.util import *
from nltk.corpus.reader.api import *

"""
Indian Language POS-Tagged Corpus
Collected by A Kumaran, Microsoft Research, India
Distributed with permission

Contents:
  - Bangla: IIT Kharagpur
  - Hindi: Microsoft Research India
  - Marathi: IIT Bombay
  - Telugu: IIIT Hyderabad
"""
class IndianCorpusReader(CorpusReader):
    """
    List of words, one per line.  Blank lines are ignored.
    """
    def words(self, fileids=...):
        ...
    
    def tagged_words(self, fileids=..., tagset=...):
        ...
    
    def sents(self, fileids=...):
        ...
    
    def tagged_sents(self, fileids=..., tagset=...):
        ...
    
    def raw(self, fileids=...):
        ...
    


class IndianCorpusView(StreamBackedCorpusView):
    def __init__(self, corpus_file, encoding, tagged, group_by_sent, tag_mapping_function=...) -> None:
        ...
    
    def read_block(self, stream):
        ...
    


