"""
This type stub file was generated by pyright.
"""

from nltk.corpus.reader.util import *
from nltk.corpus.reader.api import *
from nltk.corpus.reader.xmldocs import *

class NPSChatCorpusReader(XMLCorpusReader):
    def __init__(self, root, fileids, wrap_etree=..., tagset=...) -> None:
        ...
    
    def xml_posts(self, fileids=...):
        ...
    
    def posts(self, fileids=...):
        ...
    
    def tagged_posts(self, fileids=..., tagset=...):
        ...
    
    def words(self, fileids=...):
        ...
    
    def tagged_words(self, fileids=..., tagset=...):
        ...
    


