"""
This type stub file was generated by pyright.
"""

from nltk.lm.api import Smoothing

"""Smoothing algorithms for language modeling.

According to Chen & Goodman 1995 these should work with both Backoff and
Interpolation.
"""
class WittenBell(Smoothing):
    """Witten-Bell smoothing."""
    def __init__(self, vocabulary, counter, **kwargs) -> None:
        ...
    
    def alpha_gamma(self, word, context):
        ...
    
    def unigram_score(self, word):
        ...
    


class KneserNey(Smoothing):
    """Kneser-Ney Smoothing."""
    def __init__(self, vocabulary, counter, discount=..., **kwargs) -> None:
        ...
    
    def unigram_score(self, word):
        ...
    
    def alpha_gamma(self, word, context):
        ...
    


