"""
This type stub file was generated by pyright.
"""

"""Language Model Utilities"""
NEG_INF = ...
POS_INF = ...
def log_base2(score):
    """Convenience function for computing logarithms with base 2."""
    ...

