"""
This type stub file was generated by pyright.
"""

from nltk.tag import ClassifierBasedTagger
from nltk.chunk.api import ChunkParserI

"""
Named entity chunker
"""
class NEChunkParserTagger(ClassifierBasedTagger):
    """
    The IOB tagger used by the chunk parser.
    """
    def __init__(self, train) -> None:
        ...
    


class NEChunkParser(ChunkParserI):
    """
    Expected input: list of pos-tagged words
    """
    def __init__(self, train) -> None:
        ...
    
    def parse(self, tokens):
        """
        Each token should be a pos-tagged word
        """
        ...
    


def shape(word):
    ...

def simplify_pos(s):
    ...

def postag_tree(tree):
    ...

def load_ace_data(roots, fmt=..., skip_bnews=...):
    ...

def load_ace_file(textfile, fmt):
    ...

def cmp_chunks(correct, guessed):
    ...

def build_model(fmt=...):
    ...

if __name__ == "__main__":
    ...
