"""
This type stub file was generated by pyright.
"""

"""
Unit tests for the NLTK modules.  These tests are intended to ensure
that source code changes don't accidentally introduce bugs.
For instructions, please see:

../../web/dev/local_testing.rst

https://github.com/nltk/nltk/blob/develop/web/dev/local_testing.rst


"""
