# build
FROM node:14.16.0 as build-deps

ENV PROJECT_DIR /app/ui
WORKDIR $PROJECT_DIR

#COPY package.json yarn.lock $PROJECT_DIR
#RUN yarn
#CMD ["yarn", ""]

# FROM nginx:1.12-alpine
# COPY --from=build-deps /app/ui/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]