"""
This type stub file was generated by pyright.
"""

from nltk.parse.chart import CachedTopDownPredictRule, Chart, ChartParser, FilteredSingleEdgeFundamentalRule, SingleEdgeFundamentalRule
from nltk.parse.featurechart import FeatureChart, FeatureChartParser, FeatureSingleEdgeFundamentalRule, FeatureTopDownPredictRule

"""
Data classes and parser implementations for *incremental* chart
parsers, which use dynamic programming to efficiently parse a text.
A "chart parser" derives parse trees for a text by iteratively adding
\"edges\" to a \"chart\".  Each "edge" represents a hypothesis about the tree
structure for a subsequence of the text.  The "chart" is a
\"blackboard\" for composing and combining these hypotheses.

A parser is "incremental", if it guarantees that for all i, j where i < j,
all edges ending at i are built before any edges ending at j.
This is appealing for, say, speech recognizer hypothesis filtering.

The main parser class is ``EarleyChartParser``, which is a top-down
algorithm, originally formulated by Jay Earley (1970).
"""
class IncrementalChart(Chart):
    def initialize(self):
        ...
    
    def edges(self):
        ...
    
    def iteredges(self):
        ...
    
    def select(self, end, **restrictions):
        ...
    


class FeatureIncrementalChart(IncrementalChart, FeatureChart):
    def select(self, end, **restrictions):
        ...
    


class CompleteFundamentalRule(SingleEdgeFundamentalRule):
    ...


class CompleterRule(CompleteFundamentalRule):
    _fundamental_rule = ...
    def apply(self, chart, grammar, edge):
        ...
    


class ScannerRule(CompleteFundamentalRule):
    _fundamental_rule = ...
    def apply(self, chart, grammar, edge):
        ...
    


class PredictorRule(CachedTopDownPredictRule):
    ...


class FilteredCompleteFundamentalRule(FilteredSingleEdgeFundamentalRule):
    def apply(self, chart, grammar, edge):
        ...
    


class FeatureCompleteFundamentalRule(FeatureSingleEdgeFundamentalRule):
    ...


class FeatureCompleterRule(CompleterRule):
    _fundamental_rule = ...


class FeatureScannerRule(ScannerRule):
    _fundamental_rule = ...


class FeaturePredictorRule(FeatureTopDownPredictRule):
    ...


EARLEY_STRATEGY = ...
TD_INCREMENTAL_STRATEGY = ...
BU_INCREMENTAL_STRATEGY = ...
BU_LC_INCREMENTAL_STRATEGY = ...
LC_INCREMENTAL_STRATEGY = ...
class IncrementalChartParser(ChartParser):
    """
    An *incremental* chart parser implementing Jay Earley's
    parsing algorithm:

    | For each index end in [0, 1, ..., N]:
    |   For each edge such that edge.end = end:
    |     If edge is incomplete and edge.next is not a part of speech:
    |       Apply PredictorRule to edge
    |     If edge is incomplete and edge.next is a part of speech:
    |       Apply ScannerRule to edge
    |     If edge is complete:
    |       Apply CompleterRule to edge
    | Return any complete parses in the chart
    """
    def __init__(self, grammar, strategy=..., trace=..., trace_chart_width=..., chart_class=...) -> None:
        """
        Create a new Earley chart parser, that uses ``grammar`` to
        parse texts.

        :type grammar: CFG
        :param grammar: The grammar used to parse texts.
        :type trace: int
        :param trace: The level of tracing that should be used when
            parsing a text.  ``0`` will generate no tracing output;
            and higher numbers will produce more verbose tracing
            output.
        :type trace_chart_width: int
        :param trace_chart_width: The default total width reserved for
            the chart in trace output.  The remainder of each line will
            be used to display edges.
        :param chart_class: The class that should be used to create
            the charts used by this parser.
        """
        ...
    
    def chart_parse(self, tokens, trace=...):
        ...
    


class EarleyChartParser(IncrementalChartParser):
    def __init__(self, grammar, **parser_args) -> None:
        ...
    


class IncrementalTopDownChartParser(IncrementalChartParser):
    def __init__(self, grammar, **parser_args) -> None:
        ...
    


class IncrementalBottomUpChartParser(IncrementalChartParser):
    def __init__(self, grammar, **parser_args) -> None:
        ...
    


class IncrementalBottomUpLeftCornerChartParser(IncrementalChartParser):
    def __init__(self, grammar, **parser_args) -> None:
        ...
    


class IncrementalLeftCornerChartParser(IncrementalChartParser):
    def __init__(self, grammar, **parser_args) -> None:
        ...
    


EARLEY_FEATURE_STRATEGY = ...
TD_INCREMENTAL_FEATURE_STRATEGY = ...
BU_INCREMENTAL_FEATURE_STRATEGY = ...
BU_LC_INCREMENTAL_FEATURE_STRATEGY = ...
class FeatureIncrementalChartParser(IncrementalChartParser, FeatureChartParser):
    def __init__(self, grammar, strategy=..., trace_chart_width=..., chart_class=..., **parser_args) -> None:
        ...
    


class FeatureEarleyChartParser(FeatureIncrementalChartParser):
    def __init__(self, grammar, **parser_args) -> None:
        ...
    


class FeatureIncrementalTopDownChartParser(FeatureIncrementalChartParser):
    def __init__(self, grammar, **parser_args) -> None:
        ...
    


class FeatureIncrementalBottomUpChartParser(FeatureIncrementalChartParser):
    def __init__(self, grammar, **parser_args) -> None:
        ...
    


class FeatureIncrementalBottomUpLeftCornerChartParser(FeatureIncrementalChartParser):
    def __init__(self, grammar, **parser_args) -> None:
        ...
    


def demo(print_times=..., print_grammar=..., print_trees=..., trace=..., sent=..., numparses=...):
    """
    A demonstration of the Earley parsers.
    """
    ...

if __name__ == "__main__":
    ...
