"""
This type stub file was generated by pyright.
"""

def generate(grammar, start=..., depth=..., n=...):
    """
    Generates an iterator of all sentences from a CFG.

    :param grammar: The Grammar used to generate sentences.
    :param start: The Nonterminal from which to start generate sentences.
    :param depth: The maximal depth of the generated tree.
    :param n: The maximum number of sentences to return.
    :return: An iterator of lists of terminal tokens.
    """
    ...

demo_grammar = ...
def demo(N=...):
    ...

if __name__ == "__main__":
    ...
