"""
This type stub file was generated by pyright.
"""

"""
CHOMSKY is an aid to writing linguistic papers in the style
of the great master.  It is based on selected phrases taken
from actual books and articles written by Noam Chomsky.
Upon request, it assembles the phrases in the elegant
stylistic patterns that Chomsky is noted for.
To generate n sentences of linguistic wisdom, type

    (CHOMSKY n)  -- for example
    (CHOMSKY 5) generates half a screen of linguistic truth.
"""
leadins = ...
subjects = ...
verbs = ...
objects = ...
def generate_chomsky(times=..., line_length=...):
    ...

if __name__ == "__main__":
    ...
